# -*- coding: utf-8 -*-
"""NexusTechChatBOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5IxKS8QAxEzybC3zUoajPTbEVAy6NGL
"""

# NexusTech Mobile Support Expert System Chatbot

!pip install pyDatalog -q

from pyDatalog import pyDatalog
import re
from datetime import datetime
pyDatalog.clear()

# Define predicates
pyDatalog.create_terms('X, Y, Z, Issue, Solution, Category, Model, Symptom, Device')
pyDatalog.create_terms('has_issue, solution_for, issue_category, device_model, symptom_indicates')
pyDatalog.create_terms('warranty_status, recommended_action, troubleshooting_step')

# ==================== KNOWLEDGE BASE ====================

# 1. BATTERY ISSUES
pyDatalog.assert_fact('has_issue', 'battery_drain', 'battery')
pyDatalog.assert_fact('has_issue', 'slow_charging', 'battery')
pyDatalog.assert_fact('has_issue', 'not_charging', 'battery')
pyDatalog.assert_fact('has_issue', 'overheating_charging', 'battery')

# Battery solutions
pyDatalog.assert_fact('solution_for', 'battery_drain', 'Check battery usage in Settings > Battery. Close background apps. Reduce screen brightness. Disable location services when not needed.')
pyDatalog.assert_fact('solution_for', 'slow_charging', 'Use original NexusTech charger. Clean charging port gently. Try a different power outlet. Check cable for damage.')
pyDatalog.assert_fact('solution_for', 'not_charging', 'Restart device. Clean charging port. Try different cable/charger. Check for software updates.')
pyDatalog.assert_fact('solution_for', 'overheating_charging', 'Remove phone case while charging. Avoid using phone during charging. Charge in cool environment. Use original charger only.')

# 2. DISPLAY ISSUES
pyDatalog.assert_fact('has_issue', 'screen_frozen', 'display')
pyDatalog.assert_fact('has_issue', 'screen_flickering', 'display')
pyDatalog.assert_fact('has_issue', 'touch_not_responding', 'display')
pyDatalog.assert_fact('has_issue', 'screen_black', 'display')
pyDatalog.assert_fact('has_issue', 'screen_cracked', 'display')

# Display solutions
pyDatalog.assert_fact('solution_for', 'screen_frozen', 'Force restart: Hold Power + Volume Down for 10 seconds. If persists, boot in Safe Mode.')
pyDatalog.assert_fact('solution_for', 'screen_flickering', 'Adjust brightness settings. Disable adaptive brightness. Update display drivers. Factory reset if needed.')
pyDatalog.assert_fact('solution_for', 'touch_not_responding', 'Clean screen thoroughly. Remove screen protector temporarily. Restart device. Calibrate touch in Settings.')
pyDatalog.assert_fact('solution_for', 'screen_black', 'Charge for 30 minutes. Force restart. Check if device vibrates when turned on. May need service center visit.')
pyDatalog.assert_fact('solution_for', 'screen_cracked', 'Visit nearest NexusTech service center for screen replacement. Estimated cost: $150-$250 depending on model.')

# 3. CONNECTIVITY ISSUES
pyDatalog.assert_fact('has_issue', 'wifi_not_connecting', 'connectivity')
pyDatalog.assert_fact('has_issue', 'bluetooth_not_working', 'connectivity')
pyDatalog.assert_fact('has_issue', 'no_signal', 'connectivity')
pyDatalog.assert_fact('has_issue', 'mobile_data_slow', 'connectivity')
pyDatalog.assert_fact('has_issue', 'gps_not_working', 'connectivity')

# Connectivity solutions
pyDatalog.assert_fact('solution_for', 'wifi_not_connecting', 'Forget network and reconnect. Restart router and phone. Check if WiFi works on other devices. Reset network settings.')
pyDatalog.assert_fact('solution_for', 'bluetooth_not_working', 'Turn Bluetooth off/on. Unpair and re-pair device. Clear Bluetooth cache. Restart phone.')
pyDatalog.assert_fact('solution_for', 'no_signal', 'Toggle airplane mode. Check SIM card insertion. Contact carrier. Check for network outages in your area.')
pyDatalog.assert_fact('solution_for', 'mobile_data_slow', 'Check data limit. Move to better coverage area. Reset APN settings. Clear cache partition.')
pyDatalog.assert_fact('solution_for', 'gps_not_working', 'Enable high accuracy mode. Clear GPS cache. Check location permissions. Use GPS Status app to reset A-GPS.')

# 4. PERFORMANCE ISSUES
pyDatalog.assert_fact('has_issue', 'phone_slow', 'performance')
pyDatalog.assert_fact('has_issue', 'apps_crashing', 'performance')
pyDatalog.assert_fact('has_issue', 'phone_overheating', 'performance')
pyDatalog.assert_fact('has_issue', 'storage_full', 'performance')

# Performance solutions
pyDatalog.assert_fact('solution_for', 'phone_slow', 'Clear cache data. Uninstall unused apps. Disable animations. Update to latest software. Consider factory reset.')
pyDatalog.assert_fact('solution_for', 'apps_crashing', 'Update apps. Clear app cache/data. Uninstall and reinstall app. Check for OS updates.')
pyDatalog.assert_fact('solution_for', 'phone_overheating', 'Close background apps. Avoid direct sunlight. Remove case. Stop intensive tasks. Check for rogue apps.')
pyDatalog.assert_fact('solution_for', 'storage_full', 'Delete unused apps. Clear cache. Move photos to cloud. Use SD card. Delete old downloads.')

# 5. CAMERA ISSUES
pyDatalog.assert_fact('has_issue', 'camera_blurry', 'camera')
pyDatalog.assert_fact('has_issue', 'camera_not_opening', 'camera')
pyDatalog.assert_fact('has_issue', 'flash_not_working', 'camera')

# Camera solutions
pyDatalog.assert_fact('solution_for', 'camera_blurry', 'Clean camera lens. Tap to focus. Disable HDR. Clear camera cache. Update camera app.')
pyDatalog.assert_fact('solution_for', 'camera_not_opening', 'Restart phone. Clear camera cache. Force stop camera app. Check storage space.')
pyDatalog.assert_fact('solution_for', 'flash_not_working', 'Check flashlight works separately. Clear camera cache. Restart device. May need hardware repair.')

# 6. AUDIO ISSUES
pyDatalog.assert_fact('has_issue', 'no_sound', 'audio')
pyDatalog.assert_fact('has_issue', 'microphone_not_working', 'audio')
pyDatalog.assert_fact('has_issue', 'speaker_distorted', 'audio')

# Audio solutions
pyDatalog.assert_fact('solution_for', 'no_sound', 'Check volume settings. Restart device. Clean speaker grills. Check Do Not Disturb mode. Test with headphones.')
pyDatalog.assert_fact('solution_for', 'microphone_not_working', 'Check app permissions. Clean microphone holes. Test in different apps. Boot in Safe Mode.')
pyDatalog.assert_fact('solution_for', 'speaker_distorted', 'Clean speaker grills. Lower volume. Check audio settings. May need speaker replacement.')

# 7. SOFTWARE ISSUES
pyDatalog.assert_fact('has_issue', 'cant_update', 'software')
pyDatalog.assert_fact('has_issue', 'bootloop', 'software')
pyDatalog.assert_fact('has_issue', 'forgot_password', 'software')

# Software solutions
pyDatalog.assert_fact('solution_for', 'cant_update', 'Check storage space (need 2GB+). Connect to WiFi. Charge battery above 50%. Clear system cache.')
pyDatalog.assert_fact('solution_for', 'bootloop', 'Boot into Recovery Mode: Power + Volume Up. Wipe cache partition. Factory reset if necessary.')
pyDatalog.assert_fact('solution_for', 'forgot_password', 'Use Google Account recovery. Factory reset via Recovery Mode (erases data). Visit service center with proof of purchase.')

# Device models
pyDatalog.assert_fact('device_model', 'NexusTech Pro 12', 'flagship')
pyDatalog.assert_fact('device_model', 'NexusTech Elite 11', 'flagship')
pyDatalog.assert_fact('device_model', 'NexusTech Lite 10', 'midrange')
pyDatalog.assert_fact('device_model', 'NexusTech Spark 9', 'budget')

# Warranty information
pyDatalog.assert_fact('warranty_status', 'under_warranty', 'Free repair/replacement for manufacturing defects. Visit service center with purchase receipt.')
pyDatalog.assert_fact('warranty_status', 'out_of_warranty', 'Paid repair services available. Estimated costs provided after diagnosis.')
pyDatalog.assert_fact('warranty_status', 'accidental_damage', 'Not covered under standard warranty. Repair costs apply. Consider NexusCare insurance.')

# Define rules
solution_for(Issue, Solution) <= solution_for(Issue, Solution)
has_issue(Symptom, Category) <= has_issue(Symptom, Category)

class NexusTechSupportBot:
    def __init__(self):
        self.awaiting_sub_issue = False
        self.current_category = None

    def extract_keywords(self, user_input):
        user_input = user_input.lower()
        keywords = {
            'battery_drain': ['battery drain', 'draining'],
            'slow_charging': ['slow charging', 'charging slow'],
            'not_charging': ['not charging', 'no charging'],
            'overheating_charging': ['overheat', 'hot charging'],

            'screen_frozen': ['screen frozen', 'freeze'],
            'screen_flickering': ['flicker'],
            'touch_not_responding': ['touch not working'],
            'screen_black': ['black screen'],
            'screen_cracked': ['cracked screen'],

            'wifi_not_connecting': ['wifi', 'wi-fi'],
            'bluetooth_not_working': ['bluetooth'],
            'no_signal': ['no signal'],
            'mobile_data_slow': ['slow data'],
            'gps_not_working': ['gps'],

            'phone_slow': ['phone slow'],
            'apps_crashing': ['app crash'],
            'phone_overheating': ['overheat'],
            'storage_full': ['storage full'],

            'camera_blurry': ['blurry'],
            'camera_not_opening': ['camera not opening'],
            'flash_not_working': ['flash not working'],

            'no_sound': ['no sound'],
            'microphone_not_working': ['microphone not working'],
            'speaker_distorted': ['distorted speaker'],

            'cant_update': ['can’t update'],
            'bootloop': ['bootloop'],
            'forgot_password': ['forgot password']
        }

        detected = []
        for issue, terms in keywords.items():
            for t in terms:
                if t in user_input:
                    detected.append(issue)
                    break
        return detected

    def detect_category(self, text):
        categories = ["battery", "display", "connectivity", "performance", "camera", "audio", "software"]
        for cat in categories:
            if cat in text.lower():
                return cat
        return None

    def get_sub_issues(self, category):
        query = pyDatalog.ask(f"has_issue(Issue, '{category}')")
        if query:
            return [ans[0] for ans in query.answers]
        return []

    def get_solution(self, issue):
        query = pyDatalog.ask(f"solution_for('{issue}', Solution)")
        if query:
            return query.answers[0][0]
        return None

    def process_query(self, user_input):

        # If waiting for user to pick sub-issue
        if self.awaiting_sub_issue:
            chosen = user_input.lower()
            sub_issues = self.get_sub_issues(self.current_category)

            for issue in sub_issues:
                readable = issue.replace("_", " ")
                if readable in chosen or issue in chosen:
                    self.awaiting_sub_issue = False
                    sol = self.get_solution(issue)
                    return f"🔧 **{readable.title()}**\n{sol}"

            return "Please choose one of the listed sub-issues."

        # Detect category first
        category = self.detect_category(user_input)
        if category:
            sub_issues = self.get_sub_issues(category)
            self.awaiting_sub_issue = True
            self.current_category = category

            options = "\n".join([f"• {s.replace('_',' ').title()}" for s in sub_issues])

            return f"""
You mentioned **{category} issues**.
Please choose your exact problem:

{options}

👉 Type one of the issues above.
"""

        # Direct sub-issue detection
        detected = self.extract_keywords(user_input)
        if detected:
            issue = detected[0]
            sol = self.get_solution(issue)
            return f"🔧 **{issue.replace('_',' ').title()}**\n{sol}"

        return "I couldn't understand your issue. Please describe it more clearly."

    def greet(self):
        """Welcome message"""
        return """
╔═════════════════════════════════════════════════════════════════╗
║        🔷  Welcome to NexusTech Mobile Support Center  🔷      ║
╚═════════════════════════════════════════════════════════════════╝

Hello! I'm your NexusTech AI Support Assistant. I'm here to
help you resolve any issues with your NexusTech device.

I can assist with:
  📱 Battery & Charging Issues
  📺 Display & Touch Problems
  📡 Connectivity (WiFi, Bluetooth, Network)
  ⚡ Performance & Speed Issues
  📷 Camera & Audio Problems
  💾 Software & Update Issues

How can I help you today?
"""

def main():
    bot = NexusTechSupportBot()
    print(bot.greet())
    print("🤖 NexusTech Mobile Support Assistant Ready!")

    while True:
        user = input("\nYou: ").strip()
        if user.lower() in ["exit", "quit","bye"]:
            print("Thank you for using NexusTech Support! Goodbye 👋")
            break

        print("\nBot:", bot.process_query(user))


if __name__ == "__main__":
    main()

